]0;student@daf804b6f100: ~[01;32mstudent@daf804b6f100[00m:[01;34m~[00m$ ls -la
total 20
drwxr-xr-x 2 student student 4096 Dec  8  2021 [0m[01;34m.[0m
drwxr-xr-x 1 root    root    4096 Dec  8  2021 [01;34m..[0m
-rw-r--r-- 1 student student  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 student student 3771 Feb 25  2020 .bashrc
-rw-r--r-- 1 student student  807 Feb 25  2020 .profile
]0;student@daf804b6f100: ~[01;32mstudent@daf804b6f100[00m:[01;34m~[00m$ cd /
]0;student@daf804b6f100: /[01;32mstudent@daf804b6f100[00m:[01;34m/[00m$ ls -;a[K[K[K-la
total 68
drwxr-xr-x   1 root root 4096 Mar  6 06:08 [0m[01;34m.[0m
drwxr-xr-x   1 root root 4096 Mar  6 06:08 [01;34m..[0m
-rwxr-xr-x   1 root root    0 Mar  6 06:08 [01;32m.dockerenv[0m
lrwxrwxrwx   1 root root    7 Oct  6  2021 [01;36mbin[0m -> [01;34musr/bin[0m
drwxr-xr-x   2 root root 4096 Apr 15  2020 [01;34mboot[0m
drwxr-xr-x   2 root root 4096 Mar  6 06:08 [01;34mchallenge[0m
drwxr-xr-x   5 root root  340 Mar  6 06:08 [01;34mdev[0m
drwxr-xr-x   1 root root 4096 Mar  6 06:08 [01;34metc[0m
drwxr-xr-x   1 root root 4096 Dec  8  2021 [01;34mhome[0m
lrwxrwxrwx   1 root root    7 Oct  6  2021 [01;36mlib[0m -> [01;34musr/lib[0m
lrwxrwxrwx   1 root root    9 Oct  6  2021 [01;36mlib32[0m -> [01;34musr/lib32[0m
lrwxrwxrwx   1 root root    9 Oct  6  2021 [01;36mlib64[0m -> [01;34musr/lib64[0m
lrwxrwxrwx   1 root root   10 Oct  6  2021 [01;36mlibx32[0m -> [01;34musr/libx32[0m
drwxr-xr-x   2 root root 4096 Oct  6  2021 [01;34mmedia[0m
drwxr-xr-x   2 root root 4096 Oct  6  2021 [01;34mmnt[0m
drwxr-xr-x   2 root root 4096 Oct  6  2021 [01;34mopt[0m
dr-xr-xr-x 230 root root    0 Mar  6 06:08 [01;34mproc[0m
drwx------   2 root root 4096 Oct  6  2021 [01;34mroot[0m
drwxr-xr-x   1 root root 4096 Mar  6 06:08 [01;34mrun[0m
lrwxrwxrwx   1 root root    8 Oct  6  2021 [01;36msbin[0m -> [01;34musr/sbin[0m
drwxr-xr-x   2 root root 4096 Oct  6  2021 [01;34msrv[0m
dr-xr-xr-x  13 root root    0 Mar  6 06:08 [01;34msys[0m
drwxrwxrwt   1 root root 4096 Dec  8  2021 [30;42mtmp[0m
drwxr-xr-x   1 root root 4096 Oct  6  2021 [01;34musr[0m
drwxr-xr-x   1 root root 4096 Oct  6  2021 [01;34mvar[0m
]0;student@daf804b6f100: /[01;32mstudent@daf804b6f100[00m:[01;34m/[00m$ cd challenge/
]0;student@daf804b6f100: /challenge[01;32mstudent@daf804b6f100[00m:[01;34m/challenge[00m$ ls
setup-ftp.sh  [0m[01;32mtry-harder-ftp-service[0m  [00;36mtry-harder.mp3[0m
]0;student@daf804b6f100: /challenge[01;32mstudent@daf804b6f100[00m:[01;34m/challenge[00m$ ls -la
total 92
drwxr-xr-x 2 root root  4096 Mar  6 06:08 [0m[01;34m.[0m
drwxr-xr-x 1 root root  4096 Mar  6 06:08 [01;34m..[0m
-r--r--r-- 1 root root   272 Mar  6 06:08 setup-ftp.sh
-r-xr-xr-x 1 root root 18568 Mar  6 06:08 [01;32mtry-harder-ftp-service[0m
-r--r--r-- 1 root root 59392 Mar  6 06:08 [00;36mtry-harder.mp3[0m
]0;student@daf804b6f100: /challenge[01;32mstudent@daf804b6f100[00m:[01;34m/challenge[00m$ powershell