Linux 48b2247d38e9 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar  8 05:26:29 2023 from 192.168.119.125
┏━([1;31mMessage from Kali developers[00m)
┃
┃ This is a minimal installation of Kali Linux, you likely
┃ want to install supplementary tools. Learn how:
┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
┃
┗━([2;37mRun: “touch ~/.hushlogin” to hide this message[0m)
[?2004h]0;student@48b2247d38e9: ~[;32m┌──([1;34mstudent㉿48b2247d38e9[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m ls
[?2004l
[?2004h]0;student@48b2247d38e9: ~[;32m┌──([1;34mstudent㉿48b2247d38e9[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m chalnn      cd /challenge
[?2004l
[?2004h]0;student@48b2247d38e9: /challenge[;32m┌──([1;34mstudent㉿48b2247d38e9[;32m)-[[0;1m/challenge[;32m]
[;32m└─[1;34m$[0m ls
[?2004l[0m[01;31mflag.rar[0m

[?2004h]0;student@48b2247d38e9: /challenge[;32m┌──([1;34mstudent㉿48b2247d38e9[;32m)-[[0;1m/challenge[;32m]
[;32m└─[1;34m$[0m exit
[?2004llogout
