┏━([1;31mMessage from Kali developers[00m)
┃
┃ This is a minimal installation of Kali Linux, you likely
┃ want to install supplementary tools. Learn how:
┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
┃
┗━([2;37mRun: “touch ~/.hushlogin” to hide this message[0m)
[?2004h]0;student@de398d6b8762: ~[;32m┌──([1;34mstudent㉿de398d6b8762[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m ls
[?2004lpasswords.txt

[?2004h]0;student@de398d6b8762: ~[;32m┌──([1;34mstudent㉿de398d6b8762[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m cat passwords.txt
[?2004lzxcvbnm
edward
oliver
diana
samsung
freedom
angelo
kenneth
master
scooby
carmen
456789
sebastian
rebecca
jackie
spiderman
christopher
karina
johnny
hotmail
0123456789
school
barcelona
august
orlando
samuel
cameron
slipknot
cutiepie
monkey1
50cent
bonita
kevin
bitch
maganda
babyboy
casper
brenda
adidas
kitten
karen
mustang
isabel
natalie
cuteako
javier
789456123
123654
sarah
bowwow
portugal
laura
777777
marvin
denise
tigers
volleyball
jasper
rockstar
january
fuckoff
alicia
nicholas
flowers
cristian
tintin
bianca
chrisbrown
chester
101010
smokey
silver
internet
sweet
strawberry
garfield
dennis
panget
francis
cassie
benfica
love123
696969
asdfgh
lollipop
olivia
cancer
camila
qwertyuiop
superstar
harrypotter
charles
monique
midnight
vincent
christine
apples
scorpio
jordan23
lorena
andreea
mercedes
katherine
charmed
abigail
rafael
icecream
mexico
brianna
nirvana
aaliyah
pookie
johncena
lovelove
abcdef
benjamin
131313
gangsta
brooke
333333
hiphop
aaaaaa
mybaby
sergio
welcome
metallica
julian
travis
myspace1
babyblue
sabrina
michael1
jeffrey
stephen
love
dakota
catherine
badboy
fernanda
westlife
blondie
sasuke
smiley
jackson
simple
melanie
steaua
dolphins
roberto
fluffy
teresa
piglet
ronald
slideshow
asdfghjkl
minnie
newyork
jason
raymond
santiago
jayson
88888888
5201314
jerome
gandako
muffin
gatita
babyko
246810
sweetheart
chivas
ladybug
kitty
popcorn
alberto
valeria
cookies
leslie
jenny
nicole1
12345678910
leonardo
jayjay
liliana
dexter
232323
amores
rockon
christ
anthony1
marcus
fatima
miamor
lover
chris1

[?2004h]0;student@de398d6b8762: ~[;32m┌──([1;34mstudent㉿de398d6b8762[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m cat /etc/passwd
[?2004lroot:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
systemd-network:x:101:102:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
systemd-resolve:x:102:103:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
systemd-timesync:x:103:104:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
messagebus:x:104:105::/nonexistent:/usr/sbin/nologin
sshd:x:105:65534::/run/sshd:/usr/sbin/nologin
shadow-man:x:1000:1000::/home/shadow-man:/bin/bash
student:x:1001:1001::/home/student:/bin/bash

[?2004h]0;student@de398d6b8762: ~[;32m┌──([1;34mstudent㉿de398d6b8762[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m cat /etc/passwd               ls
[?2004lpasswords.txt

[?2004h]0;student@de398d6b8762: ~[;32m┌──([1;34mstudent㉿de398d6b8762[;32m)-[[0;1m~[;32m]
[;32m└─[1;34m$[0m exit
[?2004llogout
